#!/bin/bash

[[ ! -f "./version" ]] && {
    echo "No version file found!"
    exit 1
}

readonly version="$(cat ./version)"

commit_hash=$(git rev-parse --short HEAD 2>/dev/null || echo "nogit")
build_date=$(date +%Y%m%d)
informational_version="${version}+{CONFIG}.${build_date}.${commit_hash}"

echo "Building AssemblyInfo.Version.cs file for configuration $configuration"

cat >"./APKognito/AssemblyInfo.Version.cs" <<EOF
/*
    Generated by generate_version.sh @ $(date -u)
*/

using System.Reflection;

// Main versioning. Debug versions are constant.

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyInformationalVersion("1.0.0+DEBUG")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
#else
#if DEBUG_RELEASE
[assembly: AssemblyInformationalVersion("${informational_version//\{CONFIG\}/PublicDebug}")]
[assembly: AssemblyConfiguration("PublicDebug")]
#else
[assembly: AssemblyInformationalVersion("${informational_version//\{CONFIG\}/Release}")]
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyVersion("$version")]
[assembly: AssemblyFileVersion("$version")]
#endif

[assembly: AssemblyCompany("APKognito")]
[assembly: AssemblyProduct("APKognito")]
[assembly: AssemblyTitle("APKognito")]
[assembly: System.Runtime.Versioning.TargetPlatform("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows7.0")]
EOF

echo "Generated Assembly.Version.cs with version $version ($informational_version)"
