#!/bin/bash

[[ ! -f "./version" ]] && {
    echo "No version file found!"
    exit 1
}

readonly version="$(cat ./version)"

commit_hash=$(git rev-parse --short HEAD 2>/dev/null || echo "nogit")
build_date=$(date +%Y%m%d)
informational_version="${version}+%CONFIG%.${build_date}.${commit_hash}"

echo "Building AssemblyInfo.Version.cs file for configuration $configuration"

{
    echo -e "/*\\n\\tGenerated by generate_version.sh @ $(date -u)\\n*/\\n"
    echo "using System.Reflection;"
    echo
    echo "// Main versioning. Debug versions are constant."
    echo
    echo "#if DEBUG"
    echo "[assembly: AssemblyConfiguration(\"Debug\")]"
    echo "[assembly: AssemblyInformationalVersion(\"1.0.0+DEBUG\")]"
    echo "[assembly: AssemblyVersion(\"1.0.0\")]"
    echo "[assembly: AssemblyFileVersion(\"1.0.0\")]"
    echo "#else"
    echo "#if DEBUG_RELEASE"
    echo "[assembly: AssemblyInformationalVersion(\"${informational_version//\%CONFIG\%/PublicDebug}\")]"
    echo "[assembly: AssemblyConfiguration(\"PublicDebug\")]"
    echo "#else"
    echo "[assembly: AssemblyInformationalVersion(\"${informational_version//\%CONFIG\%/Release}\")]"
    echo "[assembly: AssemblyConfiguration(\"Release\")]"
    echo "#endif"
    echo "[assembly: AssemblyVersion(\"$version\")]"
    echo "[assembly: AssemblyFileVersion(\"$version\")]"
    echo "#endif"
    echo
    echo "[assembly: AssemblyCompany(\"APKognito\")]"
    echo "[assembly: AssemblyProduct(\"APKognito\")]"
    echo "[assembly: AssemblyTitle(\"APKognito\")]"
    echo "[assembly: System.Runtime.Versioning.TargetPlatform(\"Windows7.0\")]"
    echo "[assembly: System.Runtime.Versioning.SupportedOSPlatform(\"Windows7.0\")]"

} >"./APKognito/AssemblyInfo.Version.cs"

echo "Generated Assembly.Version.cs with version $version ($informational_version)"
