#if DEBUG
using System.IO;
using System.Reflection;
using APKognito.Utilities;
namespace APKognito.Cli;

internal static class ConfigurationDump
{
    public static void SerializeTypes(string filepath, params IEnumerable<Type> types)
    {
        List<PropertyGroup> props = [];

        foreach (Type type in types)
        {
            PropertyGroup group = new()
            {
                ClassName = type.Name,
                Properties = GetPropertyInfos(type)
            };

            FileLogger.Log($"Collected {group.Properties.Length} configurations from {type.Name}.");

            props.Add(group);
        }

        WriteOutConfigurations(filepath, props);
    }

    private static PropertyInfo[] GetPropertyInfos(Type type)
    {
        IEnumerable<PropertyInfo> props = type.GetProperties()
            .Where(p => p.GetCustomAttribute<ApkonsultSerializableAttribute>(false) is not null);

        return [.. props];
    }

    private static void WriteOutConfigurations(string filepath, List<PropertyGroup> props)
    {
        try
        {
            using Stream fileWriter = File.OpenWrite(filepath);
            using StreamWriter writer = new(fileWriter);

            writer.WriteLine("using System;\r\n");
            writer.WriteLine($"/*\r\n    This file was generated automatically at {DateTimeOffset.UtcNow}.\r\n    Do not edit this file as any changes will be overwritten.\r\n*/\r\n");
            writer.WriteLine("public sealed partial class ApkognitoConfigurationModel\r\n{\r\n");

            foreach (PropertyGroup group in props)
            {
                writer.WriteLine($"    /* {group.ClassName} */\r\n");

                foreach (PropertyInfo property in group.Properties)
                {
                    // The attribute should only be used on standard/primitive types
                    writer.WriteLine($"    public {property.PropertyType.Name}");
                }
            }
        }
        catch (Exception ex)
        {
            FileLogger.LogException("Failed to serialize collected configuration data.", ex);
            return;
        }

        FileLogger.Log("Remember to run a DB migration. Chances are you'll forget.");
    }

    private sealed record PropertyGroup
    {
        public string ClassName { get; init; } = string.Empty;

        public PropertyInfo[] Properties { get; init; } = [];
    }
}
#endif

/// <summary>
/// Unused on Release builds.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ApkonsultSerializableAttribute : Attribute;
