//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/d/AppsIWillNeverFinish/APKognito/APKognito.ApkLib/Automation/ANTLR/AutoConfig_Parser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AutoConfig_Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAutoConfig_ParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] AutoConfig_Parser.DocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.metadata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetadata([NotNull] AutoConfig_Parser.MetadataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSection([NotNull] AutoConfig_Parser.SectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] AutoConfig_Parser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] AutoConfig_Parser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.sectionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSectionDeclaration([NotNull] AutoConfig_Parser.SectionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AutoConfig_Parser.metaSetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetaSetter([NotNull] AutoConfig_Parser.MetaSetterContext context);
}
