/*
	Generated by generate_version.sh @ Sat Nov 22 23:29:45 UTC 2025
*/

using System.Reflection;

// Main versioning. Debug versions are constant.

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyInformationalVersion("1.0.0+DEBUG")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
#else
#if DEBUG_RELEASE
[assembly: AssemblyInformationalVersion("2.2.0+PublicDebug.20251122.884b525")]
[assembly: AssemblyConfiguration("PublicDebug")]
#else
[assembly: AssemblyInformationalVersion("2.2.0+Release.20251122.884b525")]
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyVersion("2.2.0")]
[assembly: AssemblyFileVersion("2.2.0")]
#endif

[assembly: AssemblyCompany("APKognito")]
[assembly: AssemblyProduct("APKognito")]
[assembly: AssemblyTitle("APKognito")]
[assembly: System.Runtime.Versioning.TargetPlatform("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows7.0")]
