/*
	Generated by generate_version.sh @ Wed May  7 21:59:19 UTC 2025
*/

using System.Reflection;

// Main versioning. Debug versions are constant.

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyInformationalVersion("1.0.0+DEBUG")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
#else
#if DEBUG_RELEASE
[assembly: AssemblyInformationalVersion("2.0.1+PublicDebug.20250507.ab28a41")]
[assembly: AssemblyConfiguration("PublicDebug")]
#else
[assembly: AssemblyInformationalVersion("2.0.1+Release.20250507.ab28a41")]
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyVersion("2.0.1")]
[assembly: AssemblyFileVersion("2.0.1")]
#endif

[assembly: AssemblyCompany("APKognito")]
[assembly: AssemblyProduct("APKognito")]
[assembly: AssemblyTitle("APKognito")]
[assembly: System.Runtime.Versioning.TargetPlatform("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows7.0")]
