global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Diagnostics.CodeAnalysis;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using Application = System.Windows.Application;
global using Brushes = System.Windows.Media.Brushes;
global using ListView = Wpf.Ui.Controls.ListView;
global using MessageBox = Wpf.Ui.Controls.MessageBox;
global using MessageBoxResult = Wpf.Ui.Controls.MessageBoxResult;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using RichTextBox = Wpf.Ui.Controls.RichTextBox;
global using Timer = System.Threading.Timer;
global using WPF = System.Windows;
